### ISSUE TITLE
uploaded script is not marked as "Script enabled" 

### ISSUE THREAD

**Issue by mi-hol** [stefanobertini/tasmota-script-support#15]
**Describe the bug**
check mark in "Script enabled"  is missing

![image](https://github.com/user-attachments/assets/0bd31c45-544a-43d7-87f6-d6087f0dbeed)

**To Reproduce**

**Expected behavior**
check mark in "Script enabled"  is set
![image](https://github.com/user-attachments/assets/83227435-7593-4a6f-b4a5-ce740f2ee489)

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows 10
- VS Code: 1.95.3
- extension: 1.0.6
![image](https://github.com/user-attachments/assets/194029ad-6b9b-4d80-a8d1-e8288f7c2006)

**Comment by stefanobertini** [comment]
I'm sorry, but it is not possible to activate that flag using the Tasmota API that allows script uploading. You must manually activate the script, which will remain active the next times you upload a file.

In any case, I believe it is appropriate that the upload function does not automatically activate the script. There could be situations where running the script before performing certain operations might actually cause an issue.

**Comment by mi-hol** [comment]
Hi Stefano, marking it as "completed" is from my view misleading because the underlying issue was actually not fixed!
I'd suggest to assign label "wont fix" and reopen it, so that other users are aware of it.
Does that make sense?

**Comment by mi-hol** [comment]
an alternative to above, might be to mention this limitation clearly in documentation
