### ISSUE TITLE
Stripping comments also removes lines where there is a semicolon somewhere

### ISSUE THREAD

**Issue by florisernst** [stefanobertini/tasmota-script-support#3]
**Describe the bug**
The "strip comments" feature is too aggressive: it also removes lines where there is a semicolon somewhere and needed (specifically in HTML code)

**To Reproduce**
The following script works fine:

```
>D
>W
<p style="color:red;">Hello world</p>
```

When I add an IP and the strip comments feature, i.e. like this,

```
>D
>W
<p style="color:red;">Hello world</p>
;IP=x.x.x.x
;stripcomments
```

it gets uploaded from VS Code as 

```
>D
>W
<p style="color:red
```

**Expected behavior**
Only actual comments are removed

**Comment by stefanobertini** [comment]
I will try to implement the handling of HTML code.
Do you have other examples to suggest of code sections where the ; does not indicate a comment?

Alternatively, I could implement a switch mechanism like
```;stripcomments on ```
and 
```;stripcomments off```
to handle unforeseen cases.

**Comment by florisernst** [comment]
Thanks for the quick feedback! I am not aware of any other cases. Nevertheless, there is a guy who writes really complex scripts for Tasmota energy meters: [https://ottelo.jimdofree.com/stromz%C3%A4hler-auslesen-tasmota/#SkriptDownload](https://ottelo.jimdofree.com/stromz%C3%A4hler-auslesen-tasmota/#SkriptDownload)

Maybe in their code there are semicolons somewhere else. I can see some in JavaScript as well.

Another thing: when I uploaded my code, I had some issues with line endings. My Windows machine uses CRLF and that resulted in some weird MQTT errors (stray blanks). Maybe it would make sense to always convert to LF only on upload (also saves bytes).

**Comment by stefanobertini** [comment]
I just released a fix for both issues...
Please, let me know.

**Comment by florisernst** [comment]
This issue has been solved, is working fine now. Thank you!
