### ISSUE TITLE
Always convert line endings to LF

### ISSUE THREAD

**Issue by stefanobertini** [stefanobertini/tasmota-script-support#5]
As reported in issue #3, modify the upload phase to always strip CR from line endings

**Comment by florisernst** [comment]
Seems not to be working. I tried it with CRLF line endings in VS Code, the uploaded file has no line endings at all ...

Test code:

```
>D
>W
<p style="color:red;">Hello world</p>
;IP=x.x.x.x
;stripcomments
```

Code appearing on the device:

```
>D>W<p style="color:red;">Hello world</p>
```

In a file with only LF line endings, upload works.
